AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters: 
  CWNamespace: 
    Description: Amazon CloudWatch custom metric namespace
    Type: String
  GlueServiceRole: 
    Description: AWS Glue Service Role with permissions to create session.
    Type: String
  Warehouse: 
    Description: warehouse is a required catalog property to determine the root path of the data warehouse in storage.
    Type: String
Globals:
  Function:
    Timeout: 360
    MemorySize: 512
Resources:
  GlueTableChangeEventBridgeRule:
      Type: AWS::Events::Rule
      Properties:
        Description: "Trigger Lambda on Glue Table State Change"
        EventPattern:
          source:
            - "aws.glue"
          detail-type:
            - "Glue Data Catalog Table State Change"
        State: "ENABLED"
        Targets:
          - Arn: !GetAtt IcebergMetricsLambda.Arn
            Id: "TargetFunction"
  IcebergMetricsLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies: 
        - CloudWatchPutMetricPolicy: {}
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
        - Statement:
          - Sid: GlueInteractiveSessionPolicy
            Effect: Allow
            Action:
            - glue:GetSession
            - glue:CreateSession
            - glue:GetStatement
            - glue:RunStatement
            - glue:GetSession
            - glue:ListStatements
            Resource: !Sub 'arn:aws:glue:*:${AWS::AccountId}:session/*'
          - Sid: IAMPassRoleForGlueIS
            Effect: Allow
            Action:
            - iam:PassRole
            Resource: !Ref GlueServiceRole
          - Sid: GlueDataCatalogPolicy
            Effect: Allow
            Action:
            - glue:GetTable
            - glue:GetTableVersion
            - glue:GetTables
            - glue:GetDatabase
            - glue:GetDatabases
            - glue:SearchTables
            - glue:GetTableVersions
            - glue:GetPartitions
            - glue:ListSessions
            Resource: '*'
      Architectures:
        - x86_64
      Environment:
        Variables:
          CW_NAMESPACE: !Ref CWNamespace
          GLUE_SERVICE_ROLE: !Ref GlueServiceRole
          SPARK_CATALOG_S3_WAREHOUSE: !Ref Warehouse

  PermissionForEventBridgeToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IcebergMetricsLambda
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt GlueTableChangeEventBridgeRule.Arn
Outputs:
  IcebergMetricsLambda:
    Description: Lambda Function ARN
    Value: !GetAtt IcebergMetricsLambda.Arn